# This file is used to set up the parameters for the data and inference process.

T: 2592000 #observation time in seconds
dt: 10 #time step in seconds
nseg: 1000 #number of segments
mod: 'log' #method to coarse grain the data

response_num: False #flag to compute the response function to a anisotropic, stationary, and Gaussian SGWB

chunk: #section dedicated to the chunk of data
  duration: 1296000 #duration of the chunk in seconds

#frange
f1: 0.0001 #minimum frequency in Hz
f2: 0.029 #maximum frequency in Hz

#file to store and read data
file: '/path/data_whittle' #file to store full data
fileAV: '/path/data_gamma' #file to store coarse grained data
folder_plot: '/path/test/'

inference: #section dedicated to the inference process
  sampler: "NUTS" #choice of the sampler
  likelihood: "Gamma" #choice of the likelihood (Gamma, Whittle)
  beta: 1 #inverse of temperature for Thermodynamical integration
  warmup: 1000 #number of warmup samples
  samples: 4000 #number of samples
  chains: 1 #number of chains
  chain_method: 'parallel' #parallel, vectorized, sequential
  adapt_matrix: True
  file:  '/path/data_gamma_bin' #file to read the data
  file_post:  '/path/result_gamma_bin.npz' #file to store the posterior samples

