# This file is used to set up the parameters for the data and inference process.

T: 6480000 #observation time in seconds
dt: 10 #time step in seconds
nseg: 2000 #number of segments
mod: 'log' #method to coarse grain the data
gen2: True
response_num: True #flag to compute the response function to a anisotropic, stationary, and Gaussian SGWB

#chunk: #section dedicated to the chunk of data
#  duration: 1296000 #duration of the chunk in seconds

#frange
f1: 0.0001 #minimum frequency in Hz
f2: 0.029 #maximum frequency in Hz

#file to store and read data
file: './bahamas/data/data_whittle' #file to store full data
fileAV: './bahamas/data/data_gamma' #file to store coarse grained data
folder_plot: './bahamas/data/'


inference:
  sampler: "nested"
  likelihood: "Gamma"
  nlive: 1000
  n_pool: 1
  checkpointing: True
  checkpoint_on_training: True
  flow_config:
  file: './bahamas/data/data_gamma'
  file_post: './bahamas/data/result_gamma.npz'

