#time array
T: 2592000  # 6 mmonths = 15768000, 1 year = 31536000, 2 year = 63072000 
dt: 10
nseg: 2000
mod: 'log'
gen2: True

response_num: True

gaps:
  #parameters for injection of modulated galaxy
  sched_gap: 25200 #7 hours
  sched_period: 1296000 #two weeks
  unsched_gap: 0 #3 days (259200), if 0 no unscheduled gap
  exp_scale: 864000 #10 days
  thresh: 86400 #1 day
  duty_cycle: 0.75

#frange
f1: 0.0001 
f2: 0.029

#file to store and read data
file: './bahamas/data/data_whittle' #file to store full data
fileAV: './bahamas/data/data_gamma' #file to store coarse grained data
folder_plot: './bahamas/data/'

inference: #section dedicated to the inference process
  sampler: "NUTS" #choice of the sampler
  likelihood: "Gamma" #choice of the likelihood (Gamma, Whittle)
  beta: 1 #inverse of temperature for Thermodynamical integration
  warmup: 1000 #number of warmup samples
  samples: 4000 #number of samples
  chains: 1 #number of chains
  chain_method: 'parallel' #parallel, vectorized, sequential
  adapt_matrix: True
  file:  './bahamas/data/data_gamma' #file to read the data
  file_post:  './bahamas/data/result_gamma.npz' #file to store the posterior samples
