name: Draft PDF
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    container:
      image: openjournals/inara:latest
    env:
      GIT_SHA: ${{ github.sha }}
      JOURNAL: 'joss'
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: inara -p -o pdf ./paper/paper.md
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper.pdf
          path: paper/paper.pdf

  scrub-metadata:
    runs-on: ubuntu-latest
    needs: paper
    steps:
      - uses: actions/checkout@v4
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: paper.pdf
          path: ./paper
      - name: Scrub Metadata
        run: |
          sudo apt-get update
          sudo apt-get install -y libimage-exiftool-perl
          exiftool -all= -r -overwrite_original -ext pdf ./paper
      - name: Upload scrubbed PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper.pdf
          path: ./paper/paper.pdf
