name: Draft PDF
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    container:
      image: openjournals/inara:latest
    env:
      GIT_SHA: $GITHUB_SHA
      JOURNAL: 'joss'
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: inara -p -o pdf ./paper/paper.md
