name: Build and Deploy Documentation

on:
  push:
    paths:
      - .github/workflows/docs.yml
      - docs/**
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme furo
      - name: Build Sphinx documentation
        working-directory: docs
        run: |
          make html
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html
          